fix: add domain_names input for zsec

diff --git a/examples/zsec b/examples/zsec
--- a/examples/zsec
+++ b/examples/zsec
@@ -213,7 +213,7 @@ fi
 
 
 
-echo "Checking AWS Environment Variables and Cloud Connector bootstrap requirements... For ZPA or brownfield/byo deployments, please stop and refer to the README and terraform.tfvars file instructions"
+echo "Checking AWS Environment Variables and Cloud Connector bootstrap requirements... For brownfield/byo deployments, please stop and refer to the README and terraform.tfvars file instructions"
 # if .zsecrc is not present we'll assume that AWS env was never set
 if [[ "$oper" == "up" && "$dtype" != base && ! -e ./.zsecrc ]]; then
     # Get MFA session token
@@ -416,7 +416,46 @@ case $cross_zone_lb_enabled in
 	* ) echo "invalid response. Please enter yes or no";;
     esac
 done 
+fi
 
+if [[ "$dtype" == "cc"* ]]; then
+   while true; do
+    read -r -p "Enable Route 53 configuration for ZPA? (yes/no): " zpa_response
+case $zpa_response in 
+	yes|y ) 
+    echo "Enabling Route 53 module..."
+    zpa_enabled=true
+    echo "export TF_VAR_zpa_enabled=$zpa_enabled" >> .zsecrc
+    break
+    ;;
+	no|n )
+    echo "No ZPA enablement..."
+    zpa_enabled=false
+    echo "export TF_VAR_zpa_enabled=$zpa_enabled" >> .zsecrc
+    break
+    ;;
+	* ) echo "invalid response. Please enter yes or no";;
+    esac
+done 
+fi
+
+if [[ "$zpa_enabled" == "true" || "$dtype" == *"zpa" ]]; then
+array=()
+domain_names_map="'{ "
+counter=0
+echo "Enter each ZPA Application Segment Domain/FQDN for Route 53 Resolver Rule..."
+while IFS= read -r -p "Enter a single ZPA Domain/FQDN. (Hit Enter when finished to continue): " domain_name; do
+    [[ $domain_name ]] || break  # break if line is empty
+    if [[ $domain_name = *" "* ]]; then
+  echo "Spaces not allowed. Please enter only one domain at a time. Delete .zsecrc file and re-run zsec up..."
+  exit 1
+    fi
+    array+=("$domain_name")
+    counter=$(( $counter + 1 ))
+    domain_names_map+="appseg$counter: \"$domain_name\", "
+done
+domain_names_map+="}'"
+echo "export TF_VAR_domain_names=${domain_names_map}" >> .zsecrc
 fi
 fi
 
