zsec aws regions validation

diff --git a/examples/zsec b/examples/zsec
--- a/examples/zsec
+++ b/examples/zsec
@@ -131,6 +131,7 @@ case $mfa_response in
     esac
 done 
 
+aws_regions=["af-south-1","ap-east-1","ap-northeast-1","ap-northeast-2","ap-northeast-3","ap-south-1","ap-southeast-1","ap-southeast-2","ca-central-1","cn-north-1","cn-northwest-1","eu-central-1","eu-north-1","eu-south-1","eu-west-1","eu-west-2","eu-west-3","me-south-1","sa-east-1","us-east-1","us-east-2","us-gov-east-1","us-gov-west-1","us-west-1","us-west-2"]
 # if .zsecrc is not present we'll assume that AWS env was never set
 if [[ $dtype == "base" && ! -e ./.zsecrc ]]; then
     # Get MFA session token
@@ -149,7 +150,14 @@ if [[ $dtype == "base" && ! -e ./.zsecrc ]]; then
     fi
     read -r -p "Enter AWS Access Key ID: " aws_key
     read -r -p "Enter AWS Secret Access Key: " aws_secret
-    read -r -p "Enter AWS Region: " aws_region
+    read -r -p "Enter AWS Region (e.g. us-west-2): " aws_region
+    if [[ ${aws_regions[*]} =~ $aws_region ]]; then
+    echo "export TF_VAR_arm_location=${aws_region}" >> .zsecrc
+    else
+    echo "Invalid AWS region name entered."
+    echo "Delete .zsecrc file and re-run zsec up..."
+    exit 1
+    fi
     echo "export AWS_ACCESS_KEY_ID=${aws_key}" > .zsecrc
     echo "export AWS_SECRET_ACCESS_KEY=${aws_secret}" >> .zsecrc
     echo "export AWS_DEFAULT_REGION=${aws_region}" >> .zsecrc
@@ -177,7 +185,14 @@ if [[ "$oper" == "up" && $dtype != base && ! -e ./.zsecrc ]]; then
     fi
     read -r -p "Enter AWS Access Key ID: " aws_key
     read -r -p "Enter AWS Secret Access Key: " aws_secret
-    read -r -p "Enter AWS Region: " aws_region
+    read -r -p "Enter AWS Region (e.g. us-west-2): " aws_region
+    if [[ ${aws_regions[*]} =~ $aws_region ]]; then
+    echo "export TF_VAR_arm_location=${aws_region}" >> .zsecrc
+    else
+    echo "Invalid AWS region name entered."
+    echo "Delete .zsecrc file and re-run zsec up..."
+    exit 1
+    fi
     echo "export AWS_ACCESS_KEY_ID=${aws_key}" > .zsecrc
     echo "export AWS_SECRET_ACCESS_KEY=${aws_secret}" >> .zsecrc
     echo "export AWS_DEFAULT_REGION=${aws_region}" >> .zsecrc
